name: mr-poll-prod

services:
  redis:
    image: redis:8.2.2
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3004"
    depends_on:
      - redis
    env_file: .env
    environment:
      - BOT_PORT="3003"
      - API_PORT="3004"
      - WEBSITE_URL="https://mrpoll.xyz"
      - REDIS_URL="redis://redis:6379"
      - REDIS_PASSWORD=""
    restart: unless-stopped
