name: mr-poll-dev

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
  redis:
    image: redis:8.2.2
    restart: unless-stopped
    ports:
      - "6379:6379"